#!/usr/bin/env bash
set -eou pipefail

declare -r container="build-${BUILDKITE_BUILD_ID}-${BUILDKITE_STEP_ID}"
echo "Cleaning up container $container"
docker kill "$container" || true
docker rm   "$container" || true
