#!/usr/bin/env bash
set -eou pipefail
IFS=$'\n\t'

declare -r master_cache_volume="cache_${BUILDKITE_AGENT_NAME}_${BUILDKITE_ORGANIZATION_SLUG}_${BUILDKITE_PIPELINE_SLUG}_${BUILDKITE_BRANCH}"
# Create volume for master branch, if not exists
docker volume create -d zockervols "$master_cache_volume"

if [[ "${BUILDKITE_REPO}" =~ (https|git)://github.com/oscoin/* ]]
then
    declare -rx DOCKER_RUNTIME=runc

    if [[ "${BUILDKITE_BRANCH}" == "master" ]]
    then
        declare -rx DOCKER_CACHE_MOUNT="type=volume,src=${master_cache_volume},dst=/cache,volume-driver=zockervols"
    else
        declare -rx DOCKER_CACHE_MOUNT="type=volume,dst=/cache,volume-driver=zockervols,volume-opt=from=${master_cache_volume}"
    fi

    # FIXME: can we ensure somehow that all variables in secrets_file are
    # prefixed by `SECRET_`?
    declare -r secrets_file="/etc/buildkite-agent/secrets"
    if test -r "$secrets_file" -a -f "$secrets_file"
    then
        set -a
        # shellcheck source=/dev/null
        . "$secrets_file"
        set +a
    fi
else
    declare -rx DOCKER_RUNTIME=kata-containers
    declare -rx DOCKER_CACHE_MOUNT="type=volume,src=${master_cache_volume},dst=/cache,volume-driver=zockervols"
fi

if [[ "${DOCKER_IMAGE}" != gcr.io/opensourcecoin/* ]]
then
    echo "Docker image ${DOCKER_IMAGE} not allowed"
    exit 1
fi

