#!/usr/bin/env bash
set -eou pipefail

mkdir -p /etc/buildkite-hooks/hooks

ln -sf /usr/local/bin/buildkite-command-wrapper /etc/buildkite-hooks/hooks/command
ln -sf /usr/local/bin/buildkite-command-wrapper /etc/buildkite-hooks/hooks/pre-checkout
ln -sf /usr/local/bin/buildkite-command-wrapper /etc/buildkite-hooks/hooks/pre-exit


services() {
    systemctl daemon-reload

    local units=(
        docker
        zockervols.socket
        docker-volume-prune.timer
        docker-system-prune.timer
    )

    local -i cpus agents

    cpus=$(nproc)
    cpus=$((cpus < 2 ? 2 : cpus))

    agents=$((cpus / 2))
    for i in $(seq 0 $((agents - 1)))
    do
        units+=("buildkite-agent@${i}")
    done

    for unit in "${units[@]}"
    do
        for cmd in enable restart
        do
            systemctl $cmd "$unit"
        done
    done
}

sops --decrypt --in-place /etc/buildkite-hooks/secrets.env
sops --decrypt --in-place /etc/systemd/system/buildkite-agent@.service.d/token.env

services
