{
 "title": "Alerts dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Block import rate 7m low",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height { kubernetes_cluster = \"ffnet\", status = \"best\" }[7m]) * 7 * 60 and on (instance) up{ kubernetes_cluster = \"ffnet\" } == 1",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block import rate 1h low",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height { kubernetes_cluster = \"ffnet\", status = \"best\" }[1h]) * 60 * 60 and on (instance) up{ kubernetes_cluster = \"ffnet\" } == 1",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nodes are up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up { kubernetes_cluster=\"ffnet\" }",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}