#!/usr/bin/env bash
set -eou pipefail
IFS=$'\n\t'

# Run pipeline upload on the host
if [[ "$BUILDKITE_COMMAND" == "buildkite-agent pipeline upload"* ]]
then
    # strip known command prefix
    args="${BUILDKITE_COMMAND#buildkite-agent pipeline upload}"
    # collect additional positional arguments
    # shellcheck disable=SC2206
    args=(${args# *})
    if [[ ${#args[@]} -gt 0 ]]
    then
        # take first argument and ensure it's a path relative to PWD
        arg="$(realpath --relative-base="$PWD" "${args[0]}")"
        arg="$(realpath --relative-base="$PWD" "$PWD/$arg")"
    else
        # otherwise, use agent defaults
        arg=""
    fi
    eval "buildkite-agent pipeline upload $arg"
    exit $?
fi

# Restrict docker images to vetted ones
: "${DOCKER_IMAGE:=}"

if [[ -n "${DOCKER_IMAGE}" && "${DOCKER_IMAGE}" != gcr.io/opensourcecoin/* ]]
then
    echo "Docker image ${DOCKER_IMAGE} not allowed"
    exit 1
fi

# Pass environment.

# Subset of the environment populated by buildkite.
#
# This avoids multi-line variables, and is driven mainly by the needs of
# codecov.io. More can be added on demand.
build_env=(
    "--env=CI"
    "--env=BUILDKITE"
    "--env=BUILDKITE_BRANCH"
    "--env=BUILDKITE_BUILD_NUMBER"
    "--env=BUILDKITE_JOB_ID"
    "--env=BUILDKITE_BUILD_URL"
    "--env=BUILDKITE_PROJECT_SLUG"
    "--env=BUILDKITE_COMMIT"
)

# Pipeline variables
#
# Using the `env` attribute in a pipeline yaml requires prefixing the variable
# names with `BUILD_`. The prefix will be removed.
for var in "${!BUILD_@}"
do
    echo "Exporting pipeline env variable '${var}' as '${var#BUILD_}'"
    build_env+=( "--env=${var#BUILD_}=${!var}" )
done

# Secret variables (as per environment hook)
for var in "${!SECRET_@}"
do
    echo "Exporting secret variable '${var}' as '${var#SECRET_}'"
    build_env+=( "--env=${var#SECRET_}=${!var}" )
done

# Volumes
declare -r tmp_size=200000000 # 200MB
volumes=(
    "--tmpfs=/tmp:rw,exec,nosuid,size=$tmp_size"
    "--mount=${DOCKER_CACHE_MOUNT}"
    "--mount=type=bind,src=${BUILDKITE_BUILD_CHECKOUT_PATH},dst=/build"
)

uid="$(id -u buildkite-builder)"
gid="$(id -g buildkite-builder)"

# Pull or build docker image

: "${DOCKER_FILE:=}"

docker pull "${DOCKER_IMAGE}" || { [[ -n "${DOCKER_FILE}" ]] && {
    declare img_cache img_context img_file img_cache_mount

    # Shared cache per agent
    img_cache="img_${BUILDKITE_AGENT_NAME}_${BUILDKITE_ORGANIZATION_SLUG}_${BUILDKITE_PIPELINE_SLUG}"
    docker volume create \
        --driver=zockervols \
        --label=build_cache \
        --opt='exec=on' \
        --opt='setuid=on' \
        --opt='quota=15GiB' \
        "$img_cache"
    # fix permissions (`img` relies on running as uid 1000)
    docker run --rm \
        --mount="type=volume,src=${img_cache},dst=/cache" \
        alpine \
        chmod 777 /cache
    # Don't forget to update this after new organizations are added/removed.
    # See [Note on CI and organizations].
    if [[ "${BUILDKITE_REPO}" == https://github.com/oscoin/* ||
          "${BUILDKITE_REPO}" == https://github.com/radicle-dev/* ]]
    then
        img_cache_mount="type=volume,src=${img_cache},dst=/cache"
    else
        # PRs get a transient cache volume
        img_cache_mount="type=volume,dst=/cache,volume-driver=zockervols,volume-opt=from=${img_cache}"
    fi

    # Re-tag DOCKER_IMAGE with current commit
    : "${DOCKER_IMAGE:=gcr.io/opensourcecoin/${BUILDKITE_PIPELINE_SLUG}-build}"
    : "${DOCKER_IMAGE%%:*}"
    : "${_%%@*}"
    DOCKER_IMAGE="${_}:${BUILDKITE_COMMIT}"

    img_context="$(dirname "$DOCKER_FILE")"
    img_context="$(realpath --relative-base="$BUILDKITE_BUILD_CHECKOUT_PATH" "$img_context")"
    img_context="$(realpath --relative-base="$BUILDKITE_BUILD_CHECKOUT_PATH" "${BUILDKITE_BUILD_CHECKOUT_PATH}/${img_context}")"
    img_file="$(basename "$DOCKER_FILE")"

    timeout \
        --kill-after="$((TIMEOUT_MINUTES + 10))m" \
        --signal=TERM \
        --verbose \
        "${TIMEOUT_MINUTES}m" \
        docker run \
            --rm \
            --name "img-${BUILDKITE_BUILD_ID}-${BUILDKITE_STEP_ID}" \
            --init \
            --mount="type=bind,src=${img_context},dst=/build,readonly" \
            --mount="$img_cache_mount" \
            --security-opt='seccomp=unconfined' \
            --security-opt='apparmor=unconfined' \
            --security-opt='systempaths=unconfined' \
            --cap-drop=ALL \
            --cap-add=SETUID \
            --cap-add=SETGID \
            --workdir=/build \
            'gcr.io/opensourcecoin/img@sha256:6a8661fc534f2341a42d6440e0c079aeaa701fe9d6c70b12280a1f8ce30b700c' \
                build \
                --file="$img_file" \
                --tag "$DOCKER_IMAGE" \
                --no-console \
                --backend=native \
                --state=/cache \
                --output="type=docker,name=${DOCKER_IMAGE}" \
                . \
    | docker load

    docker push "${DOCKER_IMAGE}"
};}

timeout \
    --kill-after="$((TIMEOUT_MINUTES + 10))m" \
    --signal=TERM \
    --verbose \
    "${TIMEOUT_MINUTES}m" \
    docker run --tty --rm \
        --name="build-${BUILDKITE_BUILD_ID}-${BUILDKITE_STEP_ID}" \
        --init \
        --read-only \
        --user="${uid}:${gid}" \
        --cap-drop=ALL \
        --security-opt=no-new-privileges \
        --runtime="${DOCKER_RUNTIME:-runc}" \
        "${volumes[@]}" \
        --workdir=/build \
        --entrypoint='' \
        "${build_env[@]}" \
        "${DOCKER_IMAGE}"  \
        /bin/sh -e -c "${BUILDKITE_COMMAND}"
