#!/usr/bin/env bash
set -eou pipefail

pushd "${BUILDKITE_BUILD_CHECKOUT_PATH}" >/dev/null

if [[ -r .buildkite/secrets.yaml && ( "${BUILDKITE_PULL_REQUEST_REPO}" == "" || "${BUILDKITE_PULL_REQUEST_REPO}" =~ $TRUSTED_UPSTREAMS_REGEX ) ]];
then
    echo "Writing secrets to ./.secrets"

    GOOGLE_APPLICATION_CREDENTIALS=/etc/gce/cred.json \
      sops \
      --output-type dotenv \
      --output .secrets \
      --decrypt .buildkite/secrets.yaml
fi

popd >/dev/null

sudo chown -R buildkite-builder "${BUILDKITE_BUILD_CHECKOUT_PATH}"
