#!/usr/bin/env bash
set -eou pipefail

pushd "${BUILDKITE_BUILD_CHECKOUT_PATH}" >/dev/null

if [[ -r .buildkite/secrets.yaml && "${TRUSTED_BUILD}" == "true" ]];
then
    echo "Writing secrets to ./.secrets"

    GOOGLE_APPLICATION_CREDENTIALS=/etc/gce/cred.json \
      sops \
      --output-type dotenv \
      --output .secrets \
      --decrypt .buildkite/secrets.yaml
fi

popd >/dev/null

sudo chown -R buildkite-builder "${BUILDKITE_BUILD_CHECKOUT_PATH}"
