#!/usr/bin/env bash
set -eou pipefail

reap() {
    local -r container="$1"
    echo "Reaping container $container"
    docker kill "$container" 2>/dev/null || true
    docker rm   "$container" 2>/dev/null || true
}

for x in img build
do
    reap "${x}-${BUILDKITE_BUILD_ID}-${BUILDKITE_STEP_ID}"
done
