#!/usr/bin/env bash
set -eou pipefail

pushd "${BUILDKITE_BUILD_CHECKOUT_PATH}"

if [[ -r .buildkite/secrets.yaml ]]
then
    sops --output-type dotenv --output .secrets --decrypt .buildkite/secrets.yaml
fi

popd
