#!/usr/bin/env bash

set -eou pipefail

: "${GCE_INSTANCE_NAME:=buildkite-agent-test-$(whoami)}"
: "${GCE_ZONE:=europe-west1-c}"
: "${GCE_MACHINE_TYPE:=c2-standard-8}"

# Comma separated list of key=value pairs.
: "${BUILDKITE_AGENT_TAGS:="queue=agent-experiment"}"

# The buildkite build ID to fetch
: "${BUILDKITE_PACKAGE_JOB:="706c531a-4a2f-4bc4-aee3-4823b8c3f9c1"}"

cloud_init="$(dirname "${BASH_SOURCE[0]}")/cloud-init.yaml"

# We’re using a custom delimiter to allow for the commas in the
# buildkite-agent-tags value. See
# https://cloud.google.com/sdk/gcloud/reference/topic/escaping
metadata="^%^buildkite-agent-tags=${BUILDKITE_AGENT_TAGS}%buildkite-package-job=${BUILDKITE_PACKAGE_JOB}"

gcloud compute instances create \
    "${GCE_INSTANCE_NAME}" \
    --project opensourcecoin \
    --machine-type="${GCE_MACHINE_TYPE}" \
    --image-project="ubuntu-os-cloud" \
    --image-family="ubuntu-2004-lts" \
    --zone="${GCE_ZONE}" \
    --service-account="buildkite-agent@opensourcecoin.iam.gserviceaccount.com" \
    --scopes="default,https://www.googleapis.com/auth/cloudkms" \
    --local-ssd="interface=nvme" \
    --preemptible \
    --metadata-from-file="user-data=${cloud_init}" \
    --metadata="$metadata"
